"""fixed tables

Revision ID: a1b9419e1595
Revises: 14ef3c0fa01d
Create Date: 2022-11-23 12:10:05.710491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b9419e1595'
down_revision = '14ef3c0fa01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4),
               existing_nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.Numeric(precision=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=4),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
